apiVersion: v1
kind: Service
metadata:
  name: self-healing-api
  namespace: self-healing
  labels:
    app: self-healing-api
spec:
  type: ClusterIP
  selector:
    app: self-healing-api
  ports:
    - name: http
      port: 80
      targetPort: http
